os: Visual Studio 2015 CTP
platform: x64
version: "{build}"

environment:
  nodejs_version: "2.2.1"
  publish_binary: false
  bin_dir: ./node_modules/electron-updater-tools/bin
  matrix:
    - ARCH: ia32
      CONF: release
    - ARCH: ia32
      CONF: debug
    - ARCH: x64
      CONF: release
    - ARCH: x64
      CONF: debug

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install -g is-property # workaround until node 2.3.1
  - npm install -g node-gyp
  - npm install
  # Publish builds when tagged
  # Or if APPVEYOR_REPO_COMMIT_MESSAGE contains [publish binary]
  - ps: if($env:APPVEYOR_REPO_TAG) { $env:PUBLISH_BINARY = 'true' }
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.contains('[publish binary]')) { $env:PUBLISH_BINARY = 'true' }

test_script:
  - npm test

build_script:
  - bash %bin_dir%/elb configure %ARCH% %CONF%

after_build:
  - node %bin_dir%/elpack --arch %ARCH% --configuration %CONF%

deploy_script:
  - if "%PUBLISH_BINARY%" == "true" ( node %bin_dir%/elpub -b evolve-bin -i %s3accessKeyId% -k %s3secretAccessKey% -a %ARCH% -C %CONF% )